modLoader="javafml"
loaderVersion="[38,)"
logoFile="diamond_spear.png"
license="All rights reserved."

[[mods]]
    modId="brass_armory"
    version="1.0.1-beta"
    displayName="Brass's Armory"
    credits="Inspired by Balkon's Weapons Mod"
    authors="Brass_herbalist, Milamber, DerToaster98, Xrated_junior, jodlodi and FireControl1847"
    description='''
A revamp of Balkon's Weapons Mod from YogBox/Tekkit days which slims down the item list slightly.
Stays true to the core of Balkon's Weapons with new item textures made by Brass_Herbalist.
'''

[[dependencies.brass_armory]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
