modLoader="javafml"
loaderVersion="[36,)"
logoFile="diamond_spear.png"
license="All rights reserved."

[[mods]]
    modId="brass_armory"
    version="${file.jarVersion}"
    displayName="Brass Armory"
    credits="Inspired by Balkon's Weapons Mod"
    authors="Brass_herbalist, Milamber, and FireControl1847"
    description='''
A revamp of Balkon's Weapons Mod from YogBox/Tekkit days which slims down the item list slightly.
Stays true to the core of Balkon's Weapons with new item textures made by Brass_Herbalist.
'''

[[dependencies.brass_armory]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
